stages:
  - compile
  - test

compile-cmake-serial:
  stage: compile
  tags:
    - gcc
  script:
    - which gcc
    - gcc --version
    - which cmake
    - cmake --version
    - mkdir build; cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DPKG_USER-PACE=ON  -DPKG_USER-PACE-AL=ON -DPKG_MANYBODY=ON ../cmake
    - cmake --build .
  artifacts:
    paths:
      - build/lmp

compile-cmake-mpi:
  stage: compile
  tags:
    - gcc
  script:
    - which gcc
    - gcc --version
    - which cmake
    - cmake --version
    - mkdir build-mpi; cd build-mpi
    - cmake -DCMAKE_BUILD_TYPE=Release -D BUILD_MPI=ON -DPKG_USER-PACE=ON -DPKG_USER-PACE-AL=ON -DPKG_MANYBODY=ON ../cmake
    - cmake --build .
    - ls -lrt
  artifacts:
    paths:
      - build-mpi/lmp

test-md-energy-conservation:
  stage: test
  tags:
    - gcc
  script:
    - cd test/md-run
    - ../../build/lmp -in in.md.forces
    - python analyse_energy_convergence.py log.lammps

test-md-Ti-energy-conservation-defaul-eval:
  stage: test
  tags:
    - gcc
  script:
    - cd test/md-run-Ti
    - ../../build/lmp -in in.md.forces
    - python analyse_energy_convergence.py log.lammps

test-md-Ti-energy-conservation-product-eval:
  stage: test
  tags:
    - gcc
  script:
    - cd test/md-run-Ti
    - ../../build/lmp -in in.md.forces.product
    - python analyse_energy_convergence.py log.lammps

test-two-atom-types:
  stage: test
  tags:
    - gcc
  script:
    - cd test/thermo
    - ../../build/lmp -in in.test
    - grep -A 2 "Step TotEng PotEng KinEng Pxx Pyy Pzz Pxy Pxz" log.lammps > en.1
    - cd ../two-types
    - ../../build/lmp -in in.test_2types
    - grep -A 2 "Step TotEng PotEng KinEng Pxx Pyy Pzz Pxy Pxz" log.lammps > en.2
    - diff en.2 ../thermo/en.1

test-two-atom-types-mpi:
  stage: test
  tags:
    - gcc
  script:
    - cd test/thermo
    - mpirun -np 2 ../../build-mpi/lmp -in in.test
    - grep -A 2 "Step TotEng PotEng KinEng Pxx Pyy Pzz Pxy Pxz" log.lammps > en.1
    - cd ../two-types
    - mpirun -np 2 ../../build-mpi/lmp -in in.test_2types
    - grep -A 2 "Step TotEng PotEng KinEng Pxx Pyy Pzz Pxy Pxz" log.lammps > en.2
    - diff en.2 ../thermo/en.1

test-md-energy-conservation-mpi:
  stage: test
  tags:
    - gcc
  script:
    - cd test/md-run
    - mpirun -np 2 ../../build-mpi/lmp -in in.md.forces
    - python analyse_energy_convergence.py log.lammps


test-md-energy-conservation-multispecies:
  stage: test
  tags:
    - gcc
  script:
    - cd test/md-run-FeCrH/
    - ../../build/lmp -in in.lammps
    - python analyse_energy_convergence.py log.lammps

test-md-energy-conservation-multispecies-mpi:
  stage: test
  tags:
    - gcc
  script:
    - cd test/md-run-FeCrH/
    - mpirun -np 2 ../../build-mpi/lmp -in in.lammps
    - python analyse_energy_convergence.py log.lammps

test-md-pace_al:
  stage: test
  tags:
    - gcc
  script:
    - cd test/md-run-Cu-ActiveLearning
    - mpirun -np 2 ../../build-mpi/lmp -in in.fcc.al